name: Lighthouse audit

on:
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start development server
        run: npm run dev &

      - name: Wait for server to start
        run: sleep 5s

      - name: run lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: 'localhost:5173'
          uploadArtifacts: true
          temporaryPublicStorage: true
