name: Lighthouse audit

on:
  push:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Start development server
        run: npm run dev &

      - name: Wait for server to start
        run: sleep 5s

      - name: Run Lighthouse audits
        run: |
          npm install -g lighthouse
          lighthouse http://localhost:5173 --output html --output-path report.html

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: lighthouse-report
          path: report.html
