name: lint check

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run eslint,prettier with airbnb
        run: npm run lint
  
  codeql:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Start CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}
        
      - name: autobuild
        uses: github/codeql-action/autobuild@v2
        
      - name: CodeQL analysis
        uses: github/codeql-action/analyze@v2
      
    
